name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

env:
  OPENAI_API_KEY: dummy_api_key

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.10"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run pytest

      - name: Linting
        run: |
          poetry run flake8
